const fs = require('fs');
const d = 'Infrastructure/Services/NoonAlertService.cs';
const nl = '\r\n';
const code = [
'using Microsoft.EntityFrameworkCore;',
'using Nirvachak_AI.Domain.Entities;',
'using Nirvachak_AI.Domain.Enums;',
'using Nirvachak_AI.Infrastructure.Data;',
'',
'namespace Nirvachak_AI.Infrastructure.Services;',
'',
'public class NoonAlertService : BackgroundService',
'{',
'    private readonly IServiceScopeFactory      _scopeFactory;',
'    private readonly ILogger<NoonAlertService> _logger;',
'    private static readonly TimeSpan NoonUtc   = TimeSpan.FromHours(6.5);',
'    private const           double   Threshold = 0.50;',
'',
'    public NoonAlertService(IServiceScopeFactory scopeFactory, ILogger<NoonAlertService> logger)",
'    { _scopeFactory = scopeFactory; _logger = logger; }',
'',
'    protected override async Task ExecuteAsync(CancellationToken stoppingToken)',
'    {',
'        _logger.LogInformation("[NoonAlert] Service started.");',
'        while (!stoppingToken.IsCancellationRequested)',
'        {',
'            var delay = TimeUntilNoon();',
'            _logger.LogInformation("[NoonAlert] Next check in {M} minutes.", (int)delay.TotalMinutes);',
'            await Task.Delay(delay, stoppingToken);',
'            if (!stoppingToken.IsCancellationRequested)',
'            {',
'                try   { await RunChecksAsync(); }',
'                catch (Exception ex) { _logger.LogError(ez, "[NoonAlert] Error during noon check."); }',
'            }',
'        }',
'    }',
'',
'    private static TimeSpan TimeUntilNoon()',
'    {',
'        var now    = DateTime.UtcNow;'t
'        var target = now.Date.Add(NoonUtc);',
'        if (target <= now) target = target.AddDays(1);',
'        return target - now;',
'    }',
'',
];
console.log(code.length + ' lines');