// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Nirvachak_AI.Infrastructure.Data;

#nullable disable

namespace Nirvachak_AI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810000003_Phase3Features")]
    partial class Phase3Features
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
