// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nirvachak_AI.Infrastructure.Data;

#nullable disable

namespace Nirvachak_AI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904123037_InitialMySql")]
    partial class InitialMySql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequiresAcknowledgement")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TargetRoles")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.AnnouncementAcknowledgement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcknowledgedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("AnnouncementId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId", "UserId")
                        .IsUnique();

                    b.ToTable("AnnouncementAcknowledgements");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AssignedBoothNumbers")
                        .HasColumnType("longtext");

                    b.Property<string>("AssignedWard")
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<int?>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<string>("EntityId")
                        .HasColumnType("longtext");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Booth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AssignedAgentName")
                        .HasColumnType("longtext");

                    b.Property<string>("AssignedAgentPhone")
                        .HasColumnType("longtext");

                    b.Property<string>("AssignedWorkerUserId")
                        .HasColumnType("longtext");

                    b.Property<string>("BoothName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("BoothNumber")
                        .HasColumnType("int");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<int>("FemaleVoters")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<int>("MaleVoters")
                        .HasColumnType("int");

                    b.Property<int>("OtherVoters")
                        .HasColumnType("int");

                    b.Property<int>("TotalVoters")
                        .HasColumnType("int");

                    b.Property<int>("VotedCount")
                        .HasColumnType("int");

                    b.Property<string>("WardNumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("Booths");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.BoothChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AgentPresent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BannerDisplayed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BoothClean")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("BoothNumber")
                        .HasColumnType("int");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneCharged")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SubmittedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("SubmittedByUserId")
                        .HasColumnType("longtext");

                    b.Property<bool>("TransportArranged")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("VoterListPrinted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId", "BoothNumber")
                        .IsUnique();

                    b.ToTable("BoothChecklists");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.BoothShiftAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoothNumber")
                        .HasColumnType("int");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShiftEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ShiftStart")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VolunteerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("BoothShiftAssignments");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.BudgetPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<decimal>("PlannedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("BudgetPlans");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.CampaignEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualAttendance")
                        .HasColumnType("int");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<int?>("ExpectedAttendance")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrganizedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("OrganizedByUserId")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TargetBoothNumbers")
                        .HasColumnType("longtext");

                    b.Property<string>("TargetWards")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("CampaignEvents");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.CompetitorActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ActivityTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<int?>("BoothNumber")
                        .HasColumnType("int");

                    b.Property<string>("CompetitorName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EstimatedCrowd")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("LoggedByUserId")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("PartyName")
                        .HasColumnType("longtext");

                    b.Property<int>("ThreatLevel")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("CompetitorActivities");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Constituency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CandidateName")
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ElectionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ElectionType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PartyName")
                        .HasColumnType("longtext");

                    b.Property<string>("PartySymbol")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Constituencies");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.ConstituencyModulePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SubModuleKey")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId", "ModuleKey", "SubModuleKey")
                        .IsUnique();

                    b.ToTable("ConstituencyModulePermissions");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.CouponPool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsIssued")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRedeemed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IssuedToVoterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RewardConfigId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CouponCode")
                        .IsUnique();

                    b.HasIndex("IssuedToVoterId");

                    b.HasIndex("RewardConfigId");

                    b.ToTable("CouponPools");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.DoorToDoorVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IssuesRaised")
                        .HasColumnType("longtext");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("SentimentAfterVisit")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VoterId")
                        .HasColumnType("int");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WorkerUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("VoterId");

                    b.ToTable("DoorToDoorVisits");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.ElectionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoothNumber")
                        .HasColumnType("int");

                    b.Property<int>("CandidateVotes")
                        .HasColumnType("int");

                    b.Property<string>("Competitor1Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("Competitor1Votes")
                        .HasColumnType("int");

                    b.Property<string>("Competitor2Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("Competitor2Votes")
                        .HasColumnType("int");

                    b.Property<string>("Competitor3Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("Competitor3Votes")
                        .HasColumnType("int");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EnteredByUserId")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<int?>("TotalVotesCast")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("ElectionResults");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.ExotelConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountSid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ApiToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExoPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SmsSenderId")
                        .HasColumnType("longtext");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("ExotelConfigs");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApprovedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("longtext");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsECCompliant")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("PayeeName")
                        .HasColumnType("longtext");

                    b.Property<string>("ReceiptPhotoPath")
                        .HasColumnType("longtext");

                    b.Property<string>("VoucherNumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.HasIndex("ExpenseDate");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.FieldReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgainstContacts")
                        .HasColumnType("int");

                    b.Property<string>("Challenges")
                        .HasColumnType("longtext");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<int>("ContactsMade")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FavourContacts")
                        .HasColumnType("int");

                    b.Property<int>("FloatingContacts")
                        .HasColumnType("int");

                    b.Property<string>("Highlights")
                        .HasColumnType("longtext");

                    b.Property<int>("IssuesLogged")
                        .HasColumnType("int");

                    b.Property<string>("PlannedForTomorrow")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReviewedByUserId")
                        .HasColumnType("longtext");

                    b.Property<string>("ReviewerNotes")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WorkerUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("FieldReports");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Grievance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedToName")
                        .HasColumnType("longtext");

                    b.Property<string>("AssignedToUserId")
                        .HasColumnType("longtext");

                    b.Property<int?>("BoothNumber")
                        .HasColumnType("int");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReportedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("ReporterPhone")
                        .HasColumnType("longtext");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("VoterId")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.HasIndex("Status");

                    b.HasIndex("VoterId");

                    b.HasIndex("ConstituencyId", "Status");

                    b.ToTable("Grievances");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Influencer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Alignment")
                        .HasColumnType("int");

                    b.Property<int?>("BoothNumber")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Community")
                        .HasColumnType("longtext");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EstimatedFollowers")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastMeetingOutcome")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastMetAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Ward")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("Influencers");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.MessageBroadcast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SentCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TargetDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("TargetFilter")
                        .HasColumnType("longtext");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<int>("TotalTargeted")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.HasIndex("TemplateId");

                    b.ToTable("MessageBroadcasts");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.MessageTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("MessageTemplates");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.PannaPramukh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<int>("BoothNumber")
                        .HasColumnType("int");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("PannaNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalVotersAssigned")
                        .HasColumnType("int");

                    b.Property<int>("VotersContacted")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("PannaPramukhs");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.PhoneCallLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CalledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CalledByName")
                        .HasColumnType("longtext");

                    b.Property<string>("CalledByUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int?>("SentimentAfterCall")
                        .HasColumnType("int");

                    b.Property<int>("VoterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.HasIndex("VoterId");

                    b.ToTable("PhoneCallLogs");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.RapidResponseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AffectedWards")
                        .HasColumnType("longtext");

                    b.Property<string>("AssignedToName")
                        .HasColumnType("longtext");

                    b.Property<string>("AssignedToUserId")
                        .HasColumnType("longtext");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LoggedByUserId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResponseText")
                        .HasColumnType("longtext");

                    b.Property<string>("Source")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("ThreatLevel")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("RapidResponseItems");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.RewardConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<string>("CouponCodePrefix")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PartnerBrand")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("RewardConfigs");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.SurveyCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("PartyAffiliation")
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("SurveyCandidates");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.SurveyCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<int?>("CouponId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<int>("VoterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("VoterId")
                        .IsUnique();

                    b.ToTable("SurveyCompletions");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.SurveyParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Symbol")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("SurveyParties");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.SurveyResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BoothNumber")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasColumnType("longtext");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("RespondedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RespondentName")
                        .HasColumnType("longtext");

                    b.Property<string>("RespondentPhone")
                        .HasColumnType("longtext");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("SurveyResponses");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.TransportVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoothNumber")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DriverPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("VehicleType")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("TransportVehicles");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.UserPushToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .HasColumnType("longtext");

                    b.Property<string>("ExpoPushToken")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Platform")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ExpoPushToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserPushTokens");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("AssignedArea")
                        .HasColumnType("longtext");

                    b.Property<string>("AssignedBoothNumbers")
                        .HasColumnType("longtext");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Task")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.HasIndex("IsActive");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.VolunteerLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AccuracyMeters")
                        .HasColumnType("double");

                    b.Property<int?>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("VolunteerLocations");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Voter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("BoothNumber")
                        .HasColumnType("int");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<int>("ElectionDayStatus")
                        .HasColumnType("int");

                    b.Property<string>("FatherHusbandName")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HouseholdId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSelfRegistered")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastContactedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NameLocal")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("PannaNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("longtext");

                    b.Property<int>("Sentiment")
                        .HasColumnType("int");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<string>("VoterId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("WardNumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("LastContactedAt");

                    b.HasIndex("Name");

                    b.HasIndex("Sentiment");

                    b.HasIndex("VoterId");

                    b.HasIndex("ConstituencyId", "BoothNumber");

                    b.HasIndex("ConstituencyId", "IsDeleted");

                    b.HasIndex("ConstituencyId", "Sentiment");

                    b.ToTable("Voters");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.VoterConsent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowCampaignOutreach")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowDataForAnalytics")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowSchemeNotifications")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowThirdPartyAdvertising")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowWhatsAppMessages")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ConsentGivenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<int>("VoterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VoterId")
                        .IsUnique();

                    b.ToTable("VoterConsents");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.VoterProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeBracket")
                        .HasColumnType("longtext");

                    b.Property<string>("CasteCategory")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Education")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("MonthlyIncomeBracket")
                        .HasColumnType("longtext");

                    b.Property<string>("Occupation")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("PreferredCandidateId")
                        .HasColumnType("int");

                    b.Property<string>("PreferredLanguage")
                        .HasColumnType("longtext");

                    b.Property<int?>("PreferredPartyId")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryConcerns")
                        .HasColumnType("longtext");

                    b.Property<string>("Religion")
                        .HasColumnType("longtext");

                    b.Property<int>("VoterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreferredCandidateId");

                    b.HasIndex("PreferredPartyId");

                    b.HasIndex("VoterId")
                        .IsUnique();

                    b.ToTable("VoterProfiles");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.VoterTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedByUserId")
                        .HasColumnType("longtext");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("VoterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VoterId", "Tag")
                        .IsUnique();

                    b.ToTable("VoterTags");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.VoterTransportRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PickupAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("PickupNotes")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestedByUserId")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int>("VoterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("VoterId");

                    b.ToTable("VoterTransportRequests");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Ward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConstituencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WardNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nirvachak_AI.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId");

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.AnnouncementAcknowledgement", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Announcement", "Announcement")
                        .WithMany("Acknowledgements")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Announcement");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Booth", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany("Booths")
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.BoothChecklist", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.BoothShiftAssignment", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nirvachak_AI.Domain.Entities.Volunteer", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.BudgetPlan", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.CampaignEvent", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.CompetitorActivity", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.ConstituencyModulePermission", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.CouponPool", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Voter", "IssuedToVoter")
                        .WithMany()
                        .HasForeignKey("IssuedToVoterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nirvachak_AI.Domain.Entities.RewardConfig", "RewardConfig")
                        .WithMany("Coupons")
                        .HasForeignKey("RewardConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssuedToVoter");

                    b.Navigation("RewardConfig");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.DoorToDoorVisit", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Voter", "Voter")
                        .WithMany("Visits")
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.ElectionResult", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.ExotelConfig", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Expense", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.FieldReport", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Grievance", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nirvachak_AI.Domain.Entities.Voter", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterId");

                    b.Navigation("Constituency");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Influencer", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.MessageBroadcast", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nirvachak_AI.Domain.Entities.MessageTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.MessageTemplate", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.PannaPramukh", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.PhoneCallLog", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nirvachak_AI.Domain.Entities.Voter", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.RapidResponseItem", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.RewardConfig", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Survey", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.SurveyCandidate", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.SurveyCompletion", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.CouponPool", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nirvachak_AI.Domain.Entities.Voter", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.SurveyParty", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.SurveyResponse", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Survey", "Survey")
                        .WithMany("Responses")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.TransportVehicle", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Volunteer", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Voter", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany("Voters")
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.VoterConsent", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Voter", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.VoterProfile", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.SurveyCandidate", "PreferredCandidate")
                        .WithMany()
                        .HasForeignKey("PreferredCandidateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nirvachak_AI.Domain.Entities.SurveyParty", "PreferredParty")
                        .WithMany()
                        .HasForeignKey("PreferredPartyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nirvachak_AI.Domain.Entities.Voter", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreferredCandidate");

                    b.Navigation("PreferredParty");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.VoterTag", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Voter", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.VoterTransportRequest", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nirvachak_AI.Domain.Entities.TransportVehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nirvachak_AI.Domain.Entities.Voter", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");

                    b.Navigation("Vehicle");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Ward", b =>
                {
                    b.HasOne("Nirvachak_AI.Domain.Entities.Constituency", "Constituency")
                        .WithMany("Wards")
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Announcement", b =>
                {
                    b.Navigation("Acknowledgements");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Constituency", b =>
                {
                    b.Navigation("Booths");

                    b.Navigation("Voters");

                    b.Navigation("Wards");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.RewardConfig", b =>
                {
                    b.Navigation("Coupons");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Survey", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Nirvachak_AI.Domain.Entities.Voter", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
